export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'

export const START_LOADING = 'START_LOADING'
export const STOP_LOADING = 'STOP_LOADING'

export const SHOW_RESPONSE_ERROR_MESSAGE = 'SHOW_RESPONSE_ERROR_MESSAGE'
export const HIDE_RESPONSE_ERROR_MESSAGE = 'HIDE_RESPONSE_ERROR_MESSAGE'

export const SHOW_CONFIRM_LOGOUT_MODAL = 'SHOW_CONFIRM_LOGOUT_MODAL'
export const HIDE_CONFIRM_LOGOUT_MODAL = 'HIDE_CONFIRM_LOGOUT_MODAL'