export const START_LOGIN = 'START_LOGIN'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'

export const SHOW_RESPONSE_ERROR_MESSAGE = 'SHOW_RESPONSE_ERROR_MESSAGE'
export const HIDE_RESPONSE_ERROR_MESSAGE = 'HIDE_RESPONSE_ERROR_MESSAGE'

export const SHOW_CONFIRM_LOGOUT_MODAL = 'SHOW_CONFIRM_LOGOUT_MODAL'
export const HIDE_CONFIRM_LOGOUT_MODAL = 'HIDE_CONFIRM_LOGOUT_MODAL'

export const START_GETTING_BOOKS_INFO = 'START_GETTING_BOOKS_INFO'
export const SET_ALL_BOOKS = 'GET_ALL_BOOKS'
export const SET_CURRENT_BOOK_INFO = 'SET_CURRENT_BOOK_INFO'
export const FINISH_GETTING_BOOKS_INFO = 'FINISH_GETTING_BOOKS_INFO'